### ISSUE TITLE
Use official namespace yii everywhere

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii-project-template#28]
`Yii 3 app template` as well as many Yii 3 packages use heavily new plugin under namespace `hiqdev\composer\...`. If this package is going to be used it should be probably moved under official namespace e.g. `yii\composer\..` , right?

Also please note that this package is optional in composer but hard coded in some packages:

https://github.com/yiisoft/yii-core/blob/master/tests/bootstrap.php#L8
https://github.com/yiisoft/active-record/blob/master/tests/bootstrap.php#L8

**Comment by samdark** [comment]
@hiqsol what do you think?

**Comment by hiqsol** [comment]
> Also please note that this package is optional in composer but hard coded in some packages

It is used in tests - yes. In a similar way as PHPUnit is.
But it is NOT required for packages to work.

**Comment by rob006** [comment]
@hiqsol Right now it looks like this plugin will be a big part of Yii ecosystem since it glues all libraries together. It may be optional in the same way as Composer is optional - you may use Yii without them, but it will be PITA, so it is required in practice. Considering that it is a quite niche library, IMO it makes sense to move it under Yiisoft for better control.
