### ISSUE TITLE
output assembled configs in `config/output`

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-project-template#31]
Or another directory, where the actual config are more "visible" for the user.

I find it rather unintuitive to look in `vendor/hiqdev/composer-config-plugin-output`.

Also "intermediate" configs should be prefixed with `_aliases.php` or even moved to a separate folder.

**Comment by samdark** [comment]
I like the idea. That would greatly contribute to overall transparency of what happens.

**Comment by schmunk42** [comment]
Related: https://github.com/hiqdev/composer-config-plugin/issues/21

The output directory should also be ignored in `.gitignore` I think. Another option for the path would be `config/.compiled`.

**Comment by kids-return** [comment]
`/runtime/config` might be a better choice

**Comment by hiqsol** [comment]
> Personally, I want to versioning configuration of my app to see how it is changing after installing/upgrading libraries. In fact, IMO it should be dev-only dependency used only to generate a configuration of application - after this, you should be able to use generated files without this plugin.

yes, the plugin allows all this

**Comment by rob006** [comment]
Does it always inlining things like DB credentials to generated file?

**Comment by hiqsol** [comment]
Yes, unfortunately, all variables are just inlined at the moment.
It could be improved but I don't have a simple solution to do it.

**Comment by rob006** [comment]
There are more issues with these files, especially related to code style (if they will become part of the project they should follow project CS rules) and readability (`yii\di\Reference::__set_state()` everywhere is confusing). 

Also the way how this plugin is used in Yii packages is a little chaotic. In this template it is [marked as dev dependency](https://github.com/yiisoft/yii-project-template/blob/6d664f04094a9e671310a8d9118a04ec7ae7ae90/composer.json#L76) while it is [clearly required to load config](https://github.com/yiisoft/yii-project-template/blob/6d664f04094a9e671310a8d9118a04ec7ae7ae90/public/index.php#L10) (not mention generate it, since config files are not versioned and needs to be generated on `composer install`). And it actually works only by accident - `yiisoft/yii-base-web` has this plugin in `require` section, so it is installed anyway even with `--no-dev` switch. And in such situation even if we implement `output-dir` and I decide to version my config, it still will not work since config generation is triggered on `composer install`, so installation of package will overwrite my config - one library which put this plugin in `require` section will break my setup. It really needs more work and maybe design changes to make it dev-only plugin.
